# ITEM FORMAT:
# @url: the URL of the texture to be used (@material should be PLAYER_HEAD).
# @material: the material of the item.
# @model-data: the custom model data id, used for custom resource packs.
# @display_name & lore: self-explanatory.
# @crafting.shaped: whether the item recipe is shaped (like WORKBENCH) or not (like FLINT_AND_STEEL).
# @crafting.ingredients: the ingredients that'll be used for the recipe. Format: MATERIAL_NAME, KEY (used for shape, see below).
# @crafting.shape: the shape that'll be used on the crafting table, using the KEY specified (only 3 lines required, spaces are used as AIR).
# @flags: which attributes to hide.
# @enchantments: the enchantments to be applied.
# @leather-color: the color of the leather armor.
# * Use a color from: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Color.html (e.g. AQUA, BLACK, etc.)
# * Use a random color with: $RANDOM
# * Use a color using RGB format: &#RRGGBB
# @damage: the amount of damage to apply to the item (maximum durability - given damage, can be $RANDOM or X-Y).
# @tipped: the potion effect the arrow will have (must be a TIPPED_ARROW).
# @amount: the amount of items.
#
# FOR FIREWORKS:
# @firework.power: the approximate power of the firework. Each level of power is half a second of flight time (from 0 to 127).
# firework-effects: a list of effects.
# firework-effects.x.type: the type or shape of the effect.
# firework-effects.x.flicker: whether the firework effect should flicker.
# firework-effects.x.trail: whether the firework effect should have a trail.
# firework-effects.x.colors: several primary colors to the firework effect.
# firework-effects.x.fade-colors: several fade colors to the firework effect.
# NOTE: More firework effects (firework stars) = more damage.
#
# $RANDOM:
# Color: a random color. (@leather-color / @firework.firework-effects.x.colors/fade-colors)
# PotionType: a random potion effect. (@tipped)
# FireworkEffect.Type: a random type or shape. (@firework.firework-effects.x.type)
# For @damage, a random value between 1 and max item durability is used.
#
# RANGED AMOUNT (X-Y): A random value between x and y. (@amount / @enchantments (level) / @firework.power)
#
# PERCENTAGE (only valid for @damage, NOT DECIMAL): X% / %X (% must be included); for example: 50% (same as %50) would be half-damage.
# NOTE: The percentage is taken from the maximum durability; this means:
# * WOODEN_SWORD max durability = 60; if @damage is 50% (60 * 0.50) -> 30. if @damage is 25% (60 * 0.25) -> 15.
# That value will be the damage added to the item; so, if @damage is %25, the new durability of the WOODEN_SWORD will be 60 - 15 = 45.
#
# In this example, the required ingredients are 7 of GOLD_INGOT and 1 of DIAMOND.
# You can use spaces to represent AIR (nothing).
# ingredients:
#   - DIAMOND, D
#   - GOLD_INGOT, G
# shape:
#   - "GDG"
#   - "G G"
#   - "GGG"
#
# USEFUL LINKS:
#
# Materials: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Flags: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/inventory/ItemFlag.html
# Enchantments: https://www.digminecraft.com/lists/enchantment_list_pc.php
# Colors: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Color.html
# FireworkEffect.Type: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/FireworkEffect.Type.html
# Effects: https://www.digminecraft.com/lists/effect_list_pc.php
# Sounds: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

# Don't touch this!
config-version: 1

# Available colors: black (more like a "dark blue") / blue / green / lightblue / orange / pink / purple / red / white / yellow
apps:
  camera:
    name: "Camera"
    color: black
  gallery:
    name: "Gallery"
    color: orange
  settings:
    name: "Settings"
    color: white
  music:
    name: "Music"
    color: red
  weather:
    name: "Weather"
    color: blue

date-format:
  # The date displayed on the lock screen.
  full: E, dd MMM yyyy
  # The hour displayed on the lock screen and on the main page.
  hour: HH:mm
  # The date used in the names of pictures (you shouldn't touch this!).
  picture: yyyy-MM-dd_HH-mm-ss

# The description of the configuration options.
settings-display:
  fingerprint-lock: "Toggle fingerprint lock"
  show-image-name-in-gallery: "Show image name in gallery"
  sound: "Toggle sound"
  change-background: "Change background"
  # %used-space% - used space.
  # %max-space% - max space.
  # %used-space-percentage% - used space (in percentage).
  storage: "Storage | Used %used-space% of %max-space% (%used-space-percentage%%)"
  power-off: "Power off"

# This will be displayed in the music player if there are less than 3 songs.
few-songs-in-player: "You have few songs in your player!"

# The error detail displayed when an error occurs.
error-dialog:
  no-function: "This app has no function yet!"
  no-space-available: "You don't have enough storage space!"
  processing-picture: "Processing current picture, wait a moment!"
  empty-default-backgrounds: "No default backgrounds yet, use one from your gallery!"
  empty-gallery: "The gallery is empty, take a picture first!"
  empty-music: "The music player is empty, get some music first!"
  image-is-already-the-background: "This image is already the background!"

# Text animation when starting the phone.
start-animation:
  enabled: true
  word: "MiPhone"
  # How many times to repeat the animation before turning on the phone.
  count: 3

# About the battery:
# * The phone battery is reduced in 2 different ways; by the screen being active, and by each picture taken with the camera.
# * When the phone screen is off, the battery won't be reduced.
# * The phone screen refresh is performed 4 times per second.
#
################################################################################
#
# Formula to get screen time (in seconds): [{max-battery} - ({extra.decrease-picture} * {estimated-pictures-taken})] / ({decrease-rate} * 4)
# Variables:
#
# {max-battery} = 100 * {multiplier}
# * The max capacity of a battery is always 100%, so we multiply 100 * {multiplier}.
# * If you want the battery to last longer, you must increase this value.
#
# {decrease-rate}
# * The value to be reduced for each quarter of a second.
#
# {extra.decrease-picture}
# * The value to reduce for each photo taken.
#
# {estimated-pictures-taken}
# * The number of pictures (estimated, may vary per player) to be taken.
#
# For example (with default values):
# {multiplier} = 100
# {decrease-rate} = 2
# {extra.decrease-picture} = 80
# {max-battery} = 100 * 100 = 10000
# {estimated-pictures-taken} = 10
#
# The formula is = [10000 - (80 * 10)] / (2 * 4)
#                = (10000 - 800) / (2 * 4)
#                = 9200 / 8
#                = 1150 (seconds)
#
# The screen time is 1150 seconds, which divided by 60 is ≈ 19.1666666667 minutes.
#
################################################################################
#
# For the charging time it's easier than that; HOWEVER, the charging method is called 2 times per second (instead of 4).
#
# Formula: {max-battery} / ({decrease-rate} * {increase-rate} * 2)
#
# For example (with default values):
# {multiplier} = 100
# {decrease-rate} = 2
# {increase-rate} = 20
# {max-battery} = 100 * 100 = 10000
#
# The formula is = 10000 / (20 * 2)
#                = 10000 / 40
#                = 250 (seconds)
#
# The charging time is 250 seconds, which divided by 60 is ≈ 4.16666666667 minutes.
battery:
  multiplier: 100
  increase-rate: 20
  decrease-rate: 2
  extra:
    decrease-picture: 80

storage:
  # The maximum capacity of the phone.
  # # Higher value allowed = 8EB (8 Exabytes)
  max-capacity: 256MB
  # In order to look more realistic, we increase the size of the photos in the gallery to make them look like they take up more space.
  picture-size-multiplier: 5000

# The most important item (you can't change the material).
phone:
  display-name: "&6MiPhone"
  lore:
    - "&7A revolutionary mobile phone."

# The charger item (you can't change the material).
wireless-charger:
  display-name: "&aWireless Charger 20W"
  crafting:
    shaped: true
    ingredients:
      - REDSTONE, R
      - ITEM_FRAME, I
    shape:
      - "RRR"
      - "RIR"
      - "RRR"

# Format: SOUND, VOLUME, PITCH
sounds:
  crack: BLOCK_GLASS_BREAK, 0.3, 1.0
  click: BLOCK_LEVER_CLICK, 0.3, 1.0
  toggle-button:
    on: BLOCK_WOODEN_BUTTON_CLICK_ON, 0.3, 1.0
    off: BLOCK_WOODEN_BUTTON_CLICK_OFF, 0.3, 1.0

# For reference, 2 is the distance if the phone is thrown by the player at the same standing level.
safe-phone-drop-distance: 2

# If the phone drop distance is higher than @safe-phone-drop-distance,
# then the chance of cracking will be = ({drop distance} - @safe-phone-drop-distance) * @crack-chance-per-drop-distance
# For example:
# If @safe-phone-drop-distance = 2 AND @crack-chance-per-drop-distance = 0.15 AND {drop distance} = 4 (which is higher than 2)
# then the final crack chance is = (4 - 2) * 0.15 = 2 * 0.15 = 0.3
crack-chance-per-drop-distance: 0.15

# If a phone falls on top of some of these blocks, it won't be damaged or cracked.
safe-drop-blocks:
  - HONEY_BLOCK
  - AZALEA
  - FLOWERING_AZALEA
  - BIG_DRIPLEAF
  - SPONGE
  - WET_SPONGE
  - HAY_BLOCK
  - $WOOL
  - $WOOL_CARPETS
  - $BEDS
  - $LEAVES

# If true, if the specified color does not exist within @colors, a random one from the @colors list will be used.
# If false, the player won't receive the phone.
random-color-if-color-does-not-exists: true

# If true, if there is no color inside @colors, a default color from the plugin will be used.
# If false, the player won't receive the phone.
default-color-if-color-list-is-empty: true

# Here you can choose the colors of the phones to be used.
# Formats: &#RRGGBB | RRR, GGG, BBB
colors:
  black: 39, 41, 42
  beige: 203,246, 150
  purple: 115, 45, 199
  white: "&#BCC5FC"
  dark-red: "&#AB0502"
  gold: "&#CB8D1B"

# The text that'll be displayed depending on the weather condition at the player's position.
weather-text:
  clear: "Clear time!"
  cloudy: "Some clouds..."
  raining: "It's raining!"
  raining-and-thundering: "A thunder storm!"
  shining: "Sun is shining."
  snowing: "Snow!"